spring:
  application:
    name: kafka-producer-avro
  kafka:
    topic: avro-topic
    producer:
      bootstrap-servers: localhost:29092
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: com.api.kafkaproduceravro.configs.CustomSerializerKafkaAvro
      properties:
        schema.registry.url: http://localhost:8085
    admin:
      properties:
        bootstrap-servers: localhost:29092
    properties:
      schema.registry.url: http://localhost:8085